# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_device_id', models.IntegerField()),
                ('action_type', models.IntegerField()),
                ('timestamp', models.DateField()),
                ('message', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('wifi_device_id', models.IntegerField()),
                ('details_json', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WifiDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('device_type_id', models.IntegerField(db_index=True)),
                ('hostname', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.CharField(max_length=24, unique=True)),
                ('extra_details_json', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deviceconfiguration',
            unique_together=set([('wifi_device_id', 'details_json')]),
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together=set([('wifi_device_id', 'action_type', 'timestamp')]),
        ),
    ]
